import { useState, useEffect } from 'react';
import { ethers } from 'ethers';
import axios from 'axios';
// 1. Import the Supabase client
import { createClient } from '@supabase/supabase-js';
import CryptocartABI from './contracts/Cryptocart.json';
import './App.css';

// 🚨 PASTE YOUR NEWEST CONTRACT ADDRESS HERE 🚨
const CONTRACT_ADDRESS = "0xcf8d3C98bf92A867156481Dc1861725A8C40B991";

// 2. Initialize the Supabase Connection
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);

function App() {
  const [account, setAccount] = useState(null);
  const [contract, setContract] = useState(null);
  const [products, setProducts] = useState([]);
  const [status, setStatus] = useState("");

  // Blockchain States
  const [newName, setNewName] = useState("");
  const [newPrice, setNewPrice] = useState("");
  const [imageFile, setImageFile] = useState(null);

  // NEW: Supabase States
  const [newCategory, setNewCategory] = useState("");
  const [newDescription, setNewDescription] = useState("");

  const connectWallet = async () => {
    if (window.ethereum) {
      try {
        const provider = new ethers.BrowserProvider(window.ethereum);
        const accounts = await provider.send("eth_requestAccounts", []);
        const signer = await provider.getSigner();
        const cryptocartContract = new ethers.Contract(CONTRACT_ADDRESS, CryptocartABI.abi, signer);

        setAccount(accounts[0]);
        setContract(cryptocartContract);
        setStatus("Wallet connected! Fetching store inventory...");
      } catch (error) {
        console.error("Connection failed:", error);
      }
    } else {
      alert("Please install MetaMask!");
    }
  };

  const fetchAllProducts = async () => {
    if (contract) {
      try {
        // STEP A: Fetch the Financial Data from the Blockchain
        const totalProducts = await contract.productCount();
        const loadedChainProducts = [];

        for (let i = 1; i <= totalProducts; i++) {
          const productData = await contract.products(i);
          loadedChainProducts.push({
            id: i,
            name: productData.name,
            price: ethers.formatEther(productData.price),
            isDelivered: productData.isDelivered,
            imageURI: productData.imageURI
          });
        }

        // STEP B: Fetch the Rich Metadata from Supabase
        const { data: dbProducts, error } = await supabase
          .from('products')
          .select('*');

        if (error) console.error("Supabase fetch error:", error);

        // STEP C: The Hybrid Merge! Match the DB info to the Blockchain info
        const mergedProducts = loadedChainProducts.map(chainProd => {
          // Find the matching row in Supabase using the blockchain_id
          const dbInfo = dbProducts?.find(db => db.blockchain_id === chainProd.id) || {};

          return {
            ...chainProd,
            category: dbInfo.category || "Uncategorized",
            description: dbInfo.description || "No description provided."
          };
        });

        setProducts(mergedProducts);
        setStatus("");
      } catch (error) {
        console.error("Failed to fetch products:", error);
      }
    }
  };

  useEffect(() => {
    fetchAllProducts();
  }, [contract]);

  const uploadToIPFS = async () => {
    if (!imageFile) return null;
    try {
      const formData = new FormData();
      formData.append("file", imageFile);
      const res = await axios.post("https://api.pinata.cloud/pinning/pinFileToIPFS", formData, {
        headers: {
          'Authorization': `Bearer ${import.meta.env.VITE_PINATA_JWT}`,
          "Content-Type": "multipart/form-data"
        }
      });
      return `https://gateway.pinata.cloud/ipfs/${res.data.IpfsHash}`;
    } catch (error) {
      console.error("Error uploading image to Pinata:", error);
      throw new Error("Image upload failed");
    }
  };

  // --- THE WEB2.5 ADD PRODUCT FLOW ---
  const addProduct = async (e) => {
    e.preventDefault();
    console.log("My Supabase URL is:", import.meta.env.VITE_SUPABASE_URL);
    console.log("My Supabase Key is:", import.meta.env.VITE_SUPABASE_ANON_KEY);
    if (contract && newName && newPrice && imageFile) {
      try {
        setStatus("1/3: Uploading image to IPFS...");
        const imageURI = await uploadToIPFS();

        setStatus("2/3: Waiting for MetaMask to approve blockchain transaction...");
        const priceInWei = ethers.parseEther(newPrice);
        const tx = await contract.addProduct(newName, priceInWei, imageURI);

        setStatus("Transaction sent! Writing to Ethereum...");
        await tx.wait();

        // --- NEW: Step 3 - Save to Supabase ---
        setStatus("3/3: Saving rich metadata to Supabase...");

        // Grab the brand new ID generated by the blockchain
        const newTotalCount = await contract.productCount();
        const newProductId = Number(newTotalCount);

        const { error: dbError } = await supabase
          .from('products')
          .insert([
            {
              blockchain_id: newProductId,
              category: newCategory,
              description: newDescription
            }
          ]);

        if (dbError) throw dbError;

        setStatus(`🎉 Success! "${newName}" added to the Web2.5 store.`);

        // Clear form
        setNewName(""); setNewPrice(""); setImageFile(null);
        setNewCategory(""); setNewDescription("");

        fetchAllProducts();
      } catch (error) {
        console.error("Add product failed:", error);
        setStatus("Failed to add product. Check console.");
      }
    } else {
      setStatus("Please fill out all required fields.");
    }
  };

  const buyProduct = async (id, priceString) => {
    if (contract) {
      try {
        setStatus(`Waiting for MetaMask to approve purchase...`);
        const priceInWei = ethers.parseEther(priceString);
        const tx = await contract.buyProduct(id, { value: priceInWei });
        setStatus("Locking funds in escrow...");
        await tx.wait();
        setStatus(`🎉 Success! Product #${id} is now locked in escrow.`);
        fetchAllProducts();
      } catch (error) {
        setStatus("Purchase failed. Make sure you aren't the seller!");
      }
    }
  };

  const confirmDelivery = async (id) => {
    if (contract) {
      try {
        setStatus(`Waiting for MetaMask to confirm delivery...`);
        const tx = await contract.confirmDelivery(id);
        setStatus("Releasing funds to the seller...");
        await tx.wait();
        setStatus(`💸 Success! Escrow unlocked.`);
        fetchAllProducts();
      } catch (error) {
        setStatus("Confirmation failed. Are you sure you are the buyer?");
      }
    }
  };

  return (
    <div className="App">
      <h1>🛒 Cryptocart: Web2.5 Edition</h1>

      {!account ? (
        <button onClick={connectWallet} className="connect-btn">
          🦊 Connect MetaMask
        </button>
      ) : (
        <div className="dashboard">
          <p className="wallet-text">Connected: <code>{account.slice(0, 6)}...{account.slice(-4)}</code></p>

          {status && <p className="status-message">{status}</p>}

          <div className="add-product-section">
            <h3>Sell an Item</h3>
            <form onSubmit={addProduct} className="add-form">
              {/* Core Blockchain Data */}
              <input type="text" placeholder="Product Name*" value={newName} onChange={(e) => setNewName(e.target.value)} required />
              <input type="number" step="0.0001" placeholder="Price in ETH*" value={newPrice} onChange={(e) => setNewPrice(e.target.value)} required />
              <input type="file" accept="image/*" onChange={(e) => setImageFile(e.target.files[0])} required className="file-input" />

              {/* NEW: Off-Chain Supabase Data */}
              <input type="text" placeholder="Category (e.g., Electronics, Apparel)" value={newCategory} onChange={(e) => setNewCategory(e.target.value)} />
              <textarea placeholder="Rich Description (Loads instantly from Supabase)" value={newDescription} onChange={(e) => setNewDescription(e.target.value)} rows="3" className="text-area-input" />

              <button type="submit" className="add-btn">Add to Web2.5 Store</button>
            </form>
          </div>

          <hr />

          <div className="store-grid">
            {products.map((item) => (
              <div key={item.id} className="product-card">
                <img src={item.imageURI} alt={item.name} className="product-image" />

                {/* NEW: Display the Supabase Metadata */}
                <span className="category-badge">{item.category}</span>
                <h2>{item.name}</h2>
                <p className="description-text">{item.description}</p>

                <p>ID: #{item.id} | Price: <strong>{item.price} ETH</strong></p>
                <p>Status: {item.isDelivered ? "✅ Delivered" : "📦 Pending / Escrow"}</p>

                {!item.isDelivered && (
                  <div className="button-group">
                    <button onClick={() => buyProduct(item.id, item.price)} className="buy-btn">Buy</button>
                    <button onClick={() => confirmDelivery(item.id)} className="confirm-btn">Confirm Delivery</button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

export default App;